### ISSUE TITLE
generate tests YAML automatically

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/ubc2#1]
How can we generate the YAML measurement manifest?

@mustafacc
@simbilod

**Comment by simbilod** [comment]
Last time there was a GUI-based app that could be downloaded at `pip install SiEPICLabTestParam3 python`

This defined a YAML file with a list of devices associated with tests:

```
Devices:
  EBeam,JoaquinMatres,Simon,2,6:
    DeviceID: EBeam,JoaquinMatres,Simon,2,6
    Electrical Coordinates: []
    Optical Coordinates:
    - 57.0
    - 5972.0
    Polarization: TE
    RoutineCheck: true
    Routines:
    - Fixed Voltage Wavelength Sweep:JoaquinSimon
    Type: device
    Wavelength: '1550'
```


And tests:


```
  Fixed Voltage Wavelength Sweep:
    Default:
      Channel A: true
      Channel B: true
      ELECflag: false
      IV: false
      Initialrange: '-20'
      Laseroutput: High power
      MaxA: ''
      MaxB: ''
      MinA: ''
      MinB: ''
      Numscans: '1'
      OPTICflag: false
      PV: false
      RV: false
      RangeDec: '20'
      ResA: ''
      ResB: ''
      Start: '1480'
      Stepsize: '1'
      Stop: '1580'
      Sweeppower: ''
      Sweepspeed: auto
      Voltages: 1, 2, 3
      Wavelengths: ''
      setvflag: true
      setwflag: false
    JoaquinSimon:
      Channel A: true
      Channel B: true
      IV: false
      Initialrange: '-20'
      Laseroutput: High power
      MaxA: 0, 0, 0, 0, 1, 1, 1, 2, 2, 3
      MaxB: 0, 1, 2, 3, 1, 2, 3, 2, 3, 3
      MinA: ''
      MinB: ''
      Numscans: '1'
      PV: false
      RV: false
      RangeDec: '20'
      ResA: ''
      ResB: ''
      Start: '1530'
      Stepsize: '0.1'
      Stop: '1570'
      Sweeppower: '0'
      Sweepspeed: auto
      VoltagesA: 0, 0, 0, 0, 1, 1, 1, 2, 2, 3
      VoltagesB: 0, 1, 2, 3, 1, 2, 3, 2, 3, 3
      Wavelengths: ''
```
